@echo off
ECHO Running Maven clean+install...
call mvn clean install > mvn-output 2>&1
ECHO Running Docker build...
call docker build -t playingdocker . > docker-output 2>&1
ECHO Running Docker container: playingdocker...
call docker run --rm -ti playingdocker