@echo off
ECHO Running Maven clean+install...
call mvn clean install > mvn-output 2>&1
FINDSTR /L /S /I /N /C:"Failed to execute goal" mvn-output
ECHO Running Docker build...
call docker build -t ianrusso777/oecdjob . > docker-output 2>&1
ECHO Running Docker container: myjob...
call docker run --rm -ti --name oecdjob ianrusso777/oecdjob