version: '2.0'
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  job:
    build: ../../job
    links:
      - redis
  rest:
    build: ../../rest/
    ports:
      - "8080:8080"
    links:
      - redis
  ui:
    build: ../../ui/
    ports:
      - "3000:80"
    links:
      - rest
volumes:
  logvolume01: {}